### PR TITLE
deps: bump @ipld/dag-cbor to 8.0.0

### PR DESCRIPTION
**Pull request by achingbrain**
# deps: bump @ipld/dag-cbor to 8.0.0

## Description

Following on from #28 - update @ipld/dag-cbor to same multiformats version as the rest of the module

## How Has This Been Tested?

- [x] Unit tests in module pass

## Definition of Done

Before submitting this PR, please make sure:

- [x] The work addresses the description and outcomes in the issue
- [ ] I have added relevant tests for new or updated functionality
- [ ] My code follows conventions, is well commented, and easy to understand
- [x] My code builds and tests pass without any errors or warnings
- [ ] I have tagged the relevant reviewers
- [ ] I have updated the READMEs of affected packages
- [ ] I have made corresponding changes to the documentation
- [ ] The changes have been communicated to interested parties

## References:

#28

### CODE REVIEW

**Comment by achingbrain** [comment]
cc @ukstv sorry - one more small one

**Comment by ukstv** [comment]
Okay, going to release a major version soon.

**Comment by achingbrain** [comment]
The other thing is that the CID instances in @ipld/dag-cbor 8 come from multiformats 10 which was the upgrade in #28/dag-jose@3.0.0 so a patch to 3.0.1 would make sense as now everything is multiformats 10.

**Comment by ukstv** [comment]
Sweet! 3.0.1 is released!

**Pull request merged**
